#!/usr/bin/env python3
"""gen_report_auditor.py — G13: Generate report consistency auditor from project.yaml.

Reads the audit section from project.yaml and produces a scripts/audit_report.py
script that performs machine-verifiable checks from the REPORT_CONSISTENCY_SPEC
template: title quality, abstract word count, paragraph length, jargon first-use,
terminology consistency, declarative headers, figure/table cross-refs, citation
completeness, no-new-results-in-Discussion, caption quality, build check, page
count, and URL escaping.

Usage:
    python scripts/generators/gen_report_auditor.py project.yaml [--output scripts/audit_report.py]
"""
import argparse
from pathlib import Path

import yaml


def load_project(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_report_auditor(project: dict, output_path: str) -> str:
    """Generate audit_report.py content from project.yaml."""
    audit = project.get("audit", {})
    project_name = project.get("project", {}).get("name", "Experiment")

    tsr = audit.get("ten_simple_rules", {})
    abstract_word_limit = tsr.get("abstract_word_limit", 250)
    max_paragraph_sentences = tsr.get("max_paragraph_sentences", 8)

    # Jargon terms — list of dicts with term/definition or just strings
    jargon_terms_raw = tsr.get("jargon_terms", [])
    jargon_lines = []
    for entry in jargon_terms_raw:
        if isinstance(entry, dict):
            term = entry.get("term", "")
            definition = entry.get("definition", "")
            jargon_lines.append(f'        {{"term": {repr(term)}, "definition": {repr(definition)}}},')
        else:
            jargon_lines.append(f'        {{"term": {repr(str(entry))}, "definition": ""}},')
    jargon_block = "\n".join(jargon_lines) if jargon_lines else "        # No jargon terms configured"

    # Terminology lock — list of dicts with canonical/rejected
    terminology_lock_raw = tsr.get("terminology_lock", [])
    term_lock_lines = []
    for entry in terminology_lock_raw:
        if isinstance(entry, dict):
            canonical = entry.get("canonical", "")
            rejected = entry.get("rejected", [])
            if isinstance(rejected, str):
                rejected = [rejected]
            term_lock_lines.append(
                f'        {{"canonical": {repr(canonical)}, "rejected": {repr(rejected)}}},'
            )
    term_lock_block = "\n".join(term_lock_lines) if term_lock_lines else "        # No terminology lock configured"

    # Build settings
    build = audit.get("build", {})
    page_limit = build.get("page_limit", 10)
    overfull_threshold = build.get("overfull_threshold", 10)

    # Build the config header as an f-string (small, controlled)
    config_block = f'''
# ---------------------------------------------------------------------------
# Configuration (derived from project.yaml at generation time)
# ---------------------------------------------------------------------------

ABSTRACT_WORD_LIMIT = {abstract_word_limit}
MAX_PARAGRAPH_SENTENCES = {max_paragraph_sentences}
PAGE_LIMIT = {page_limit}
OVERFULL_THRESHOLD = {overfull_threshold}

JARGON_TERMS = [
{jargon_block}
    ]

TERMINOLOGY_LOCK = [
{term_lock_block}
    ]
'''

    # The rest of the script is a plain string — no f-string interpolation needed
    # We only inject project_name into the docstring via concatenation
    content = (
        '#!/usr/bin/env python3\n'
        '"""audit_report.py — Report consistency auditor.\n'
        '\n'
        'Auto-generated by gen_report_auditor.py from project.yaml.\n'
        'Re-run generator after changing project.yaml audit configuration.\n'
        '\n'
        f'Project: {project_name}\n'
        '\n'
        'Checks performed:\n'
        '  1.  Title check (Rule 1) — reject procedural title patterns\n'
        '  2.  Abstract word count (Rule 5)\n'
        '  3.  Paragraph length (Rule 3)\n'
        '  4.  Jargon first-use (Rule 2)\n'
        '  5.  Terminology consistency (Rule 4)\n'
        '  6.  Section headers declarative (Rule 7)\n'
        '  7.  Figure/table cross-refs — orphan detection\n'
        '  8.  Citation completeness — orphan detection\n'
        '  9.  No new results in Discussion (Rule 8)\n'
        '  10. Caption quality\n'
        '  11. Build check (pdflatex)\n'
        '  12. Page count\n'
        '  13. URL escaping\n'
        '\n'
        'Exit codes:\n'
        '  0 — All checks passed (no CRITICAL/HIGH findings)\n'
        '  1 — One or more CRITICAL/HIGH findings\n'
        '"""\n'
        'import argparse\n'
        'import os\n'
        'import re\n'
        'import subprocess\n'
        'import sys\n'
        'from pathlib import Path\n'
        '\n'
        + config_block +
        _SCRIPT_BODY
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    out.chmod(0o755)

    # Summary
    print(f"Generated: {output_path}")
    print(f"  Project:            {project_name}")
    print(f"  Abstract limit:     {abstract_word_limit} words")
    print(f"  Max para sentences: {max_paragraph_sentences}")
    print(f"  Page limit:         {page_limit}")
    print(f"  Jargon terms:       {len(jargon_terms_raw)}")
    print(f"  Terminology locks:  {len(terminology_lock_raw)}")
    print(f"  Checks:             13 (title, abstract, paragraphs, jargon, "
          f"terminology, headers, crossrefs, citations, discussion, "
          f"captions, build, pages, URLs)")
    return content


# ---------------------------------------------------------------------------
# Template body for the generated script (plain string, no interpolation)
# ---------------------------------------------------------------------------

_SCRIPT_BODY = r'''
REJECTED_TITLE_PREFIXES = [
    "Analysis of",
    "A Study of",
    "Investigation of",
    "Exploring",
    "An Examination of",
]

GERUND_HEADER_RE = re.compile(
    r"^(?:#+\s*|\\(?:sub)*section\{)"
    r"\s*(Analyzing|Applying|Building|Calculating|Clustering|Comparing|"
    r"Computing|Creating|Describing|Designing|Detecting|Determining|"
    r"Discussing|Evaluating|Examining|Experimenting|Exploring|"
    r"Extending|Extracting|Finding|Fitting|Generating|Identifying|"
    r"Implementing|Improving|Investigating|Learning|Measuring|"
    r"Modeling|Modelling|Observing|Optimizing|Performing|Plotting|"
    r"Predicting|Preprocessing|Processing|Reducing|Running|Selecting|"
    r"Showing|Solving|Studying|Testing|Training|Tuning|Understanding|"
    r"Using|Validating|Verifying|Visualizing)"
)

# Bare method name headers (just a method name, no claim)
BARE_METHOD_RE = re.compile(
    r"^(?:#+\s*|\\(?:sub)*section\{)"
    r"\s*(PCA|K-Means|KMeans|GMM|DBSCAN|SVM|Random Forest|"
    r"Decision Tree|Logistic Regression|Linear Regression|"
    r"Neural Network|CNN|RNN|LSTM|Gradient Descent|"
    r"Experiment \d+|Method \d+|Results?|Discussion|Approach)\s*\}?$",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Severity levels
# ---------------------------------------------------------------------------

CRITICAL = "CRITICAL"
HIGH = "HIGH"
MEDIUM = "MEDIUM"
LOW = "LOW"


# ---------------------------------------------------------------------------
# Report reading utilities
# ---------------------------------------------------------------------------

def read_report(report_path: Path) -> str:
    """Read report file and return full text."""
    return report_path.read_text(encoding="utf-8", errors="replace")


def is_latex(report_path: Path) -> bool:
    return report_path.suffix.lower() in (".tex", ".latex")


def extract_title_latex(text: str) -> str | None:
    """Extract title from LaTeX \\title{...}."""
    m = re.search(r"\\title\{([^{}]+)\}", text)
    if m:
        return m.group(1).strip()
    # Handle multi-line title
    m = re.search(r"\\title\{(.+?)\}", text, re.DOTALL)
    if m:
        return " ".join(m.group(1).split()).strip()
    return None


def extract_title_md(text: str) -> str | None:
    """Extract title from first # heading in Markdown."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and not stripped.startswith("## "):
            return stripped[2:].strip()
    return None


def extract_abstract_latex(text: str) -> str | None:
    """Extract abstract text from LaTeX."""
    m = re.search(
        r"\\begin\{abstract\}(.+?)\\end\{abstract\}",
        text, re.DOTALL,
    )
    if m:
        return m.group(1).strip()
    return None


def extract_abstract_md(text: str) -> str | None:
    """Extract abstract section from Markdown (text under ## Abstract)."""
    lines = text.splitlines()
    in_abstract = False
    abstract_lines = []
    for line in lines:
        stripped = line.strip()
        if re.match(r"^##\s+Abstract", stripped, re.IGNORECASE):
            in_abstract = True
            continue
        if in_abstract:
            if re.match(r"^##\s+", stripped):
                break
            abstract_lines.append(line)
    if abstract_lines:
        return "\n".join(abstract_lines).strip()
    return None


def get_sections_latex(text: str) -> dict[str, str]:
    """Split LaTeX into sections by \\section{...}."""
    sections = {}
    pattern = re.compile(r"\\section\{([^{}]+)\}")
    parts = pattern.split(text)
    # parts = [preamble, name1, body1, name2, body2, ...]
    for i in range(1, len(parts) - 1, 2):
        name = parts[i].strip()
        body = parts[i + 1] if i + 1 < len(parts) else ""
        sections[name] = body
    return sections


def get_sections_md(text: str) -> dict[str, str]:
    """Split Markdown into sections by ## headings."""
    sections = {}
    lines = text.splitlines()
    current_name = None
    current_lines: list[str] = []
    for line in lines:
        m = re.match(r"^##\s+(.+)", line)
        if m:
            if current_name is not None:
                sections[current_name] = "\n".join(current_lines)
            current_name = m.group(1).strip()
            current_lines = []
        else:
            current_lines.append(line)
    if current_name is not None:
        sections[current_name] = "\n".join(current_lines)
    return sections


def get_paragraphs(text: str) -> list[tuple[int, str]]:
    """Split text into paragraphs. Returns list of (approx_line, paragraph_text)."""
    paragraphs = []
    lines = text.splitlines()
    current: list[str] = []
    start_line = 1
    for i, line in enumerate(lines, start=1):
        stripped = line.strip()
        # Paragraph break: blank line or LaTeX \par
        if not stripped or stripped == "\\par":
            if current:
                paragraphs.append((start_line, " ".join(current)))
                current = []
            start_line = i + 1
        else:
            # Skip comment lines and headings
            if stripped.startswith("%") or stripped.startswith("#"):
                if current:
                    paragraphs.append((start_line, " ".join(current)))
                    current = []
                start_line = i + 1
                continue
            # Skip LaTeX commands that are structural
            if re.match(r"\\(begin|end|section|subsection|label|caption)\{", stripped):
                if current:
                    paragraphs.append((start_line, " ".join(current)))
                    current = []
                start_line = i + 1
                continue
            current.append(stripped)
    if current:
        paragraphs.append((start_line, " ".join(current)))
    return paragraphs


def count_sentences(text: str) -> int:
    """Approximate sentence count in a paragraph."""
    # Remove common abbreviations that contain dots
    cleaned = text
    for abbr in ("e.g.", "i.e.", "et al.", "Fig.", "Eq.", "vs.", "Dr.", "Mr.", "Mrs.", "Prof."):
        cleaned = cleaned.replace(abbr, abbr.replace(".", ""))
    # Count sentence-ending punctuation
    count = len(re.findall(r"[.!?]+(?:\s|$)", cleaned))
    return max(count, 1)  # at least 1 sentence if text exists


def extract_numbers_from_text(text: str) -> set[str]:
    """Extract all numeric values from text as canonical strings."""
    nums = set()
    for m in re.finditer(r"(?<!\\)\b(\d+(?:\.\d+)?)\b", text):
        nums.add(m.group(1))
    return nums


# ---------------------------------------------------------------------------
# Check implementations
# ---------------------------------------------------------------------------

class Finding:
    def __init__(self, check: str, severity: str, message: str, line: int = 0):
        self.check = check
        self.severity = severity
        self.message = message
        self.line = line
        self.passed = severity == "PASS"

    def __repr__(self):
        loc = f" (line {self.line})" if self.line else ""
        return f"[{self.severity}] {self.check}{loc}: {self.message}"


def check_title(text: str, latex: bool) -> list[Finding]:
    """Check 1: Title is declarative, not procedural."""
    findings = []
    title = extract_title_latex(text) if latex else extract_title_md(text)
    if title is None:
        findings.append(Finding("title_check", MEDIUM, "Could not extract title from report"))
        return findings

    for prefix in REJECTED_TITLE_PREFIXES:
        if title.lower().startswith(prefix.lower()):
            findings.append(Finding(
                "title_check", HIGH,
                f"Title starts with rejected pattern \"{prefix}\": \"{title}\""
            ))
            return findings

    findings.append(Finding("title_check", "PASS", f"Title is declarative: \"{title}\""))
    return findings


def check_abstract_word_count(text: str, latex: bool) -> list[Finding]:
    """Check 2: Abstract word count within limit."""
    findings = []
    abstract = extract_abstract_latex(text) if latex else extract_abstract_md(text)
    if abstract is None:
        findings.append(Finding("abstract_word_count", MEDIUM, "Could not extract abstract"))
        return findings

    # Strip LaTeX commands for word counting
    clean = re.sub(r"\\[a-zA-Z]+\{[^{}]*\}", " ", abstract)
    clean = re.sub(r"\\[a-zA-Z]+", " ", clean)
    clean = re.sub(r"[{}\\$]", " ", clean)
    words = clean.split()
    count = len(words)

    if count > ABSTRACT_WORD_LIMIT:
        findings.append(Finding(
            "abstract_word_count", HIGH,
            f"Abstract has {count} words (limit: {ABSTRACT_WORD_LIMIT})"
        ))
    else:
        findings.append(Finding(
            "abstract_word_count", "PASS",
            f"Abstract has {count} words (limit: {ABSTRACT_WORD_LIMIT})"
        ))
    return findings


def check_paragraph_length(text: str) -> list[Finding]:
    """Check 3: No paragraph exceeds max sentence count."""
    findings = []
    paragraphs = get_paragraphs(text)
    violations = 0
    for line_num, para in paragraphs:
        if len(para.split()) < 10:
            continue  # skip very short paragraphs
        scount = count_sentences(para)
        if scount > MAX_PARAGRAPH_SENTENCES:
            violations += 1
            snippet = para[:100] + "..." if len(para) > 100 else para
            findings.append(Finding(
                "paragraph_length", MEDIUM,
                f"Paragraph has {scount} sentences (max: {MAX_PARAGRAPH_SENTENCES}): "
                f"\"{snippet}\"",
                line=line_num,
            ))
    if violations == 0:
        findings.append(Finding(
            "paragraph_length", "PASS",
            f"All paragraphs within {MAX_PARAGRAPH_SENTENCES}-sentence limit"
        ))
    return findings


def check_jargon_first_use(text: str) -> list[Finding]:
    """Check 4: Each jargon term is defined on first occurrence."""
    findings = []
    if not JARGON_TERMS:
        findings.append(Finding("jargon_first_use", "PASS", "No jargon terms configured"))
        return findings

    lines = text.splitlines()

    for entry in JARGON_TERMS:
        term = entry["term"]
        definition = entry.get("definition", "")
        if not term:
            continue

        term_lower = term.lower()

        # Find first occurrence line
        first_line = None
        first_line_num = 0
        for i, line in enumerate(lines, start=1):
            if term_lower in line.lower():
                first_line = line
                first_line_num = i
                break

        if first_line is None:
            findings.append(Finding(
                "jargon_first_use", LOW,
                f"Jargon term \"{term}\" not found in report",
            ))
            continue

        # Check if definition appears near first use (within ~200 chars)
        text_lower = text.lower()
        idx = text_lower.find(term_lower)
        if idx == -1:
            continue

        context_start = max(0, idx - 50)
        context_end = min(len(text), idx + len(term) + 200)
        context = text[context_start:context_end].lower()

        # Look for definition text, parenthetical, or common definition patterns
        has_definition = False
        if definition:
            has_definition = definition.lower() in context
        # Also accept parenthetical glosses: "term (definition)" or "term — definition"
        paren_pattern = re.compile(
            re.escape(term_lower) + r"\s*[\(\[]",
            re.IGNORECASE,
        )
        dash_pattern = re.compile(
            re.escape(term_lower) + r"\s*[—–-]\s*\w",
            re.IGNORECASE,
        )
        if paren_pattern.search(context) or dash_pattern.search(context):
            has_definition = True

        if has_definition:
            findings.append(Finding(
                "jargon_first_use", "PASS",
                f"\"{term}\" defined on first use (line {first_line_num})",
                line=first_line_num,
            ))
        else:
            findings.append(Finding(
                "jargon_first_use", MEDIUM,
                f"\"{term}\" used at line {first_line_num} without nearby definition",
                line=first_line_num,
            ))
    return findings


def check_terminology_consistency(text: str) -> list[Finding]:
    """Check 5: Rejected term variants are not used."""
    findings = []
    if not TERMINOLOGY_LOCK:
        findings.append(Finding("terminology_consistency", "PASS", "No terminology lock configured"))
        return findings

    lines = text.splitlines()
    found_violations = False

    for entry in TERMINOLOGY_LOCK:
        canonical = entry["canonical"]
        rejected = entry.get("rejected", [])
        for variant in rejected:
            if not variant:
                continue
            # Search for the rejected variant (case-insensitive, whole word)
            pattern = re.compile(r"\b" + re.escape(variant) + r"\b", re.IGNORECASE)
            for i, line in enumerate(lines, start=1):
                if pattern.search(line):
                    found_violations = True
                    findings.append(Finding(
                        "terminology_consistency", HIGH,
                        f"Rejected variant \"{variant}\" found (use \"{canonical}\" instead)",
                        line=i,
                    ))

    if not found_violations:
        findings.append(Finding(
            "terminology_consistency", "PASS",
            "All terminology consistent with canonical terms"
        ))
    return findings


def check_section_headers(text: str, latex: bool) -> list[Finding]:
    """Check 6: Section headers are declarative (not gerunds/bare method names)."""
    findings = []
    lines = text.splitlines()
    violations = 0

    for i, line in enumerate(lines, start=1):
        stripped = line.strip()
        # Detect headers
        is_header = False
        if latex:
            if re.match(r"\\(?:sub)*section\{", stripped):
                is_header = True
        else:
            if re.match(r"^#{1,4}\s+", stripped):
                is_header = True

        if not is_header:
            continue

        if GERUND_HEADER_RE.match(stripped):
            violations += 1
            findings.append(Finding(
                "section_headers", MEDIUM,
                f"Header starts with gerund: \"{stripped.strip()}\"",
                line=i,
            ))
        elif BARE_METHOD_RE.match(stripped):
            violations += 1
            findings.append(Finding(
                "section_headers", MEDIUM,
                f"Header is bare method name without claim: \"{stripped.strip()}\"",
                line=i,
            ))

    if violations == 0:
        findings.append(Finding(
            "section_headers", "PASS",
            "All section headers are declarative"
        ))
    return findings


def check_figure_table_crossrefs(text: str, latex: bool) -> list[Finding]:
    """Check 7: All \\ref{fig:X}/\\ref{tab:X} have matching \\label{} and vice versa."""
    findings = []

    if not latex:
        # For Markdown, skip this check (no \ref/\label convention)
        findings.append(Finding(
            "figure_table_crossrefs", "PASS",
            "Markdown report — LaTeX cross-ref check skipped"
        ))
        return findings

    # Collect \label{fig:X} and \label{tab:X}
    labels_fig = set(re.findall(r"\\label\{(fig:[^{}]+)\}", text))
    labels_tab = set(re.findall(r"\\label\{(tab:[^{}]+)\}", text))

    # Collect \ref{fig:X} and \ref{tab:X}
    refs_fig = set(re.findall(r"\\ref\{(fig:[^{}]+)\}", text))
    refs_tab = set(re.findall(r"\\ref\{(tab:[^{}]+)\}", text))

    all_labels = labels_fig | labels_tab
    all_refs = refs_fig | refs_tab

    # Orphan refs (referenced but never labeled)
    orphan_refs = all_refs - all_labels
    for ref in sorted(orphan_refs):
        findings.append(Finding(
            "figure_table_crossrefs", CRITICAL,
            f"\\ref{{{ref}}} referenced but no \\label{{{ref}}} found"
        ))

    # Orphan labels (labeled but never referenced)
    orphan_labels = all_labels - all_refs
    for label in sorted(orphan_labels):
        findings.append(Finding(
            "figure_table_crossrefs", HIGH,
            f"\\label{{{label}}} defined but never referenced with \\ref{{}}"
        ))

    if not orphan_refs and not orphan_labels:
        findings.append(Finding(
            "figure_table_crossrefs", "PASS",
            f"All {len(all_labels)} labels referenced, all {len(all_refs)} refs resolved"
        ))
    return findings


def check_citation_completeness(text: str, latex: bool) -> list[Finding]:
    """Check 8: All \\cite{X} have matching bibliography entries and vice versa."""
    findings = []

    if not latex:
        findings.append(Finding(
            "citation_completeness", "PASS",
            "Markdown report — LaTeX citation check skipped"
        ))
        return findings

    # Collect \cite{key1,key2,...}
    cited_keys: set[str] = set()
    for m in re.finditer(r"\\cite[tp]*\{([^{}]+)\}", text):
        for key in m.group(1).split(","):
            cited_keys.add(key.strip())

    # Collect \bibitem{key}
    bib_keys: set[str] = set()
    for m in re.finditer(r"\\bibitem\{([^{}]+)\}", text):
        bib_keys.add(m.group(1).strip())

    # Check for .bib file usage
    uses_bibtex = bool(re.search(r"\\bibliography\{", text))

    if not cited_keys:
        findings.append(Finding(
            "citation_completeness", LOW,
            "No \\cite{} commands found in report"
        ))
        return findings

    if uses_bibtex and not bib_keys:
        # Using bibtex — we cannot fully verify without parsing .bib file
        findings.append(Finding(
            "citation_completeness", LOW,
            f"Report uses \\bibliography{{}}; {len(cited_keys)} cite keys found. "
            "Cannot verify against .bib file — run bibtex for full check."
        ))
        return findings

    if bib_keys:
        orphan_cites = cited_keys - bib_keys
        orphan_bibs = bib_keys - cited_keys

        for key in sorted(orphan_cites):
            findings.append(Finding(
                "citation_completeness", CRITICAL,
                f"\\cite{{{key}}} has no matching \\bibitem{{}}"
            ))

        for key in sorted(orphan_bibs):
            findings.append(Finding(
                "citation_completeness", MEDIUM,
                f"\\bibitem{{{key}}} defined but never cited"
            ))

        if not orphan_cites and not orphan_bibs:
            findings.append(Finding(
                "citation_completeness", "PASS",
                f"All {len(cited_keys)} citations resolved, "
                f"all {len(bib_keys)} bibliography entries cited"
            ))
    else:
        findings.append(Finding(
            "citation_completeness", LOW,
            f"{len(cited_keys)} \\cite{{}} keys found but no \\bibitem{{}} entries "
            "(may use external .bib file)"
        ))

    return findings


def check_no_new_results_in_discussion(text: str, latex: bool) -> list[Finding]:
    """Check 9: No numeric values in Discussion that do not appear in Results."""
    findings = []

    sections = get_sections_latex(text) if latex else get_sections_md(text)

    # Find Results and Discussion sections (case-insensitive match)
    results_text = ""
    discussion_text = ""
    for name, body in sections.items():
        name_lower = name.lower().strip()
        if "result" in name_lower and "discussion" not in name_lower:
            results_text += body + "\n"
        if "discussion" in name_lower:
            discussion_text += body + "\n"

    if not discussion_text:
        findings.append(Finding(
            "no_new_results_discussion", "PASS",
            "No Discussion section found (or empty) — check skipped"
        ))
        return findings

    results_numbers = extract_numbers_from_text(results_text)
    discussion_numbers = extract_numbers_from_text(discussion_text)

    # Filter out very common numbers (0, 1, 2, etc.)
    trivial = {"0", "1", "2", "3", "4", "5", "10", "100"}
    new_in_discussion = discussion_numbers - results_numbers - trivial

    if new_in_discussion:
        sample = sorted(new_in_discussion)[:10]
        findings.append(Finding(
            "no_new_results_discussion", HIGH,
            f"{len(new_in_discussion)} numeric value(s) in Discussion not in Results: "
            f"{', '.join(sample)}"
        ))
    else:
        findings.append(Finding(
            "no_new_results_discussion", "PASS",
            "No new numeric values introduced in Discussion"
        ))
    return findings


def check_caption_quality(text: str, latex: bool) -> list[Finding]:
    """Check 10: Captions contain interpretation, not just 'Figure N' or 'Table N'."""
    findings = []

    if latex:
        # \caption{...}
        captions = re.findall(r"\\caption\{([^{}]+)\}", text)
    else:
        # Markdown: lines starting with "Figure N" or "Table N" after images
        captions = re.findall(
            r"(?:^|\n)\s*(?:Figure|Table)\s+\d+[.:]?\s*(.*)",
            text,
        )

    if not captions:
        findings.append(Finding(
            "caption_quality", "PASS",
            "No captions found in report"
        ))
        return findings

    weak_caption_re = re.compile(
        r"^\s*(?:Figure|Table)\s+\d+[.:]?\s*$",
        re.IGNORECASE,
    )
    # Also flag captions that are just "Figure N shows X" without interpretation
    shows_only_re = re.compile(
        r"^\s*(?:Figure|Table)\s+\d+\s+(?:shows|displays|presents|illustrates)\b",
        re.IGNORECASE,
    )

    weak_count = 0
    for cap in captions:
        cap_stripped = cap.strip()
        if weak_caption_re.match(cap_stripped):
            weak_count += 1
            findings.append(Finding(
                "caption_quality", MEDIUM,
                f"Caption lacks interpretation: \"{cap_stripped[:80]}\"",
            ))
        elif shows_only_re.match(cap_stripped) and len(cap_stripped.split()) < 8:
            weak_count += 1
            findings.append(Finding(
                "caption_quality", LOW,
                f"Caption may lack interpretation (very short): \"{cap_stripped[:80]}\"",
            ))

    if weak_count == 0:
        findings.append(Finding(
            "caption_quality", "PASS",
            f"All {len(captions)} captions contain interpretive content"
        ))
    return findings


def check_build(report_path: Path) -> list[Finding]:
    """Check 11: If .tex, attempt pdflatex compilation."""
    findings = []

    if not is_latex(report_path):
        findings.append(Finding(
            "build_check", "PASS",
            "Non-LaTeX report — build check skipped"
        ))
        return findings

    # Check if pdflatex is available
    try:
        subprocess.run(
            ["pdflatex", "--version"],
            capture_output=True, timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        findings.append(Finding(
            "build_check", LOW,
            "pdflatex not found — build check skipped"
        ))
        return findings

    # Run pdflatex in nonstopmode
    try:
        result = subprocess.run(
            [
                "pdflatex",
                "-interaction=nonstopmode",
                "-halt-on-error",
                str(report_path.name),
            ],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(report_path.parent),
        )

        if result.returncode != 0:
            # Extract first error
            error_lines = []
            for line in result.stdout.splitlines():
                if line.startswith("!"):
                    error_lines.append(line)
                    if len(error_lines) >= 3:
                        break

            error_msg = "; ".join(error_lines) if error_lines else "pdflatex exited with error"
            findings.append(Finding(
                "build_check", CRITICAL,
                f"pdflatex compilation failed: {error_msg}"
            ))
        else:
            # Check for warnings
            warnings_list = []
            overfull_count = 0
            for line in result.stdout.splitlines():
                if "Overfull" in line:
                    # Extract point value if present
                    m = re.search(r"(\d+\.?\d*)pt", line)
                    if m and float(m.group(1)) > OVERFULL_THRESHOLD:
                        overfull_count += 1
                elif "Warning" in line and "Font" not in line:
                    warnings_list.append(line.strip()[:120])

            if overfull_count > 0:
                findings.append(Finding(
                    "build_check", MEDIUM,
                    f"{overfull_count} overfull hbox warnings exceed {OVERFULL_THRESHOLD}pt threshold"
                ))

            if warnings_list:
                findings.append(Finding(
                    "build_check", LOW,
                    f"{len(warnings_list)} LaTeX warnings: {warnings_list[0]}"
                ))

            if overfull_count == 0 and not warnings_list:
                findings.append(Finding(
                    "build_check", "PASS",
                    "pdflatex compilation succeeded with no significant warnings"
                ))
            elif overfull_count == 0:
                findings.append(Finding(
                    "build_check", "PASS",
                    "pdflatex compilation succeeded"
                ))

    except subprocess.TimeoutExpired:
        findings.append(Finding(
            "build_check", HIGH,
            "pdflatex compilation timed out (>120s)"
        ))

    return findings


def check_page_count(report_path: Path) -> list[Finding]:
    """Check 12: PDF page count within limit."""
    findings = []

    # Look for a PDF with the same stem
    pdf_path = report_path.with_suffix(".pdf")
    if not pdf_path.exists():
        # Also check in parent directory
        for candidate in report_path.parent.glob("*.pdf"):
            pdf_path = candidate
            break

    if not pdf_path.exists():
        findings.append(Finding(
            "page_count", LOW,
            f"No PDF found at {pdf_path} — page count check skipped"
        ))
        return findings

    # Try to get page count
    page_count = None

    # Method 1: pdfinfo
    try:
        result = subprocess.run(
            ["pdfinfo", str(pdf_path)],
            capture_output=True, text=True, timeout=10,
        )
        for line in result.stdout.splitlines():
            if line.startswith("Pages:"):
                page_count = int(line.split(":")[1].strip())
                break
    except (FileNotFoundError, subprocess.TimeoutExpired, ValueError):
        pass

    # Method 2: python parsing (count /Type /Page)
    if page_count is None:
        try:
            raw = pdf_path.read_bytes()
            page_count = len(re.findall(rb"/Type\s*/Page(?!s)", raw))
        except Exception:
            pass

    if page_count is None:
        findings.append(Finding(
            "page_count", LOW,
            "Could not determine PDF page count"
        ))
        return findings

    if page_count > PAGE_LIMIT:
        findings.append(Finding(
            "page_count", HIGH,
            f"PDF has {page_count} pages (limit: {PAGE_LIMIT})"
        ))
    else:
        findings.append(Finding(
            "page_count", "PASS",
            f"PDF has {page_count} pages (limit: {PAGE_LIMIT})"
        ))
    return findings


def check_url_escaping(text: str, latex: bool) -> list[Finding]:
    """Check 13: No unescaped # in \\url{} or \\href{}."""
    findings = []

    if not latex:
        findings.append(Finding(
            "url_escaping", "PASS",
            "Non-LaTeX report — URL escaping check skipped"
        ))
        return findings

    lines = text.splitlines()
    violations = 0

    for i, line in enumerate(lines, start=1):
        # Find \url{...} and \href{...}
        for m in re.finditer(r"\\(?:url|href)\{([^{}]+)\}", line):
            url = m.group(1)
            # Check for unescaped # (not preceded by \)
            for j, ch in enumerate(url):
                if ch == "#" and (j == 0 or url[j - 1] != "\\"):
                    violations += 1
                    findings.append(Finding(
                        "url_escaping", HIGH,
                        f"Unescaped # in URL: \"{url[:80]}\"",
                        line=i,
                    ))
                    break  # one finding per URL

    if violations == 0:
        findings.append(Finding(
            "url_escaping", "PASS",
            "All URLs properly escaped"
        ))
    return findings


# ---------------------------------------------------------------------------
# Phase mapping
# ---------------------------------------------------------------------------

# Phase 0-3: structural checks only
# Phase 4: post-draft checks (writing quality + cross-refs)
# Phase 5: pre-submission (all checks including build)
# "full": all checks

PHASE_CHECKS = {
    0: ["title_check", "terminology_consistency"],
    1: ["title_check", "terminology_consistency"],
    2: ["title_check", "terminology_consistency"],
    3: ["title_check", "terminology_consistency", "jargon_first_use"],
    4: [
        "title_check", "abstract_word_count", "paragraph_length",
        "jargon_first_use", "terminology_consistency",
        "section_headers", "figure_table_crossrefs", "citation_completeness",
        "no_new_results_discussion", "caption_quality",
    ],
    5: [
        "title_check", "abstract_word_count", "paragraph_length",
        "jargon_first_use", "terminology_consistency",
        "section_headers", "figure_table_crossrefs", "citation_completeness",
        "no_new_results_discussion", "caption_quality",
        "build_check", "page_count", "url_escaping",
    ],
}

ALL_CHECKS = {
    "title_check": check_title,
    "abstract_word_count": check_abstract_word_count,
    "paragraph_length": check_paragraph_length,
    "jargon_first_use": check_jargon_first_use,
    "terminology_consistency": check_terminology_consistency,
    "section_headers": check_section_headers,
    "figure_table_crossrefs": check_figure_table_crossrefs,
    "citation_completeness": check_citation_completeness,
    "no_new_results_discussion": check_no_new_results_in_discussion,
    "caption_quality": check_caption_quality,
    "build_check": lambda text, latex: [],  # placeholder — handled separately
    "page_count": lambda text, latex: [],    # placeholder — handled separately
    "url_escaping": check_url_escaping,
}


# ---------------------------------------------------------------------------
# FINDINGS.md output
# ---------------------------------------------------------------------------

def write_findings_md(findings: list[Finding], output_path: Path, report_path: Path, phase: str) -> None:
    """Write findings to FINDINGS.md."""
    lines = [
        "# Report Audit Findings",
        "",
        f"**Report:** `{report_path}`",
        f"**Phase:** {phase}",
        f"**Checks run:** {len(set(f.check for f in findings))}",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]

    by_severity = {}
    for f in findings:
        by_severity.setdefault(f.severity, []).append(f)

    for sev in [CRITICAL, HIGH, MEDIUM, LOW, "PASS"]:
        count = len(by_severity.get(sev, []))
        lines.append(f"- **{sev}:** {count}")
    lines.append("")

    # Per-check verdicts
    lines.append("## Per-Check Verdicts")
    lines.append("")
    lines.append("| Check | Verdict | Details |")
    lines.append("|-------|---------|---------|")

    check_names_seen = []
    for f in findings:
        if f.check not in check_names_seen:
            check_names_seen.append(f.check)

    for check_name in check_names_seen:
        check_findings = [f for f in findings if f.check == check_name]
        worst = "PASS"
        for sev in [CRITICAL, HIGH, MEDIUM, LOW]:
            if any(f.severity == sev for f in check_findings):
                worst = sev
                break
        # Pick first non-PASS finding for details, or PASS message
        detail_f = next(
            (f for f in check_findings if f.severity != "PASS"),
            check_findings[0] if check_findings else None,
        )
        detail = detail_f.message[:100] if detail_f else ""
        verdict = "PASS" if worst == "PASS" else f"**FAIL** ({worst})"
        lines.append(f"| {check_name} | {verdict} | {detail} |")

    lines.append("")

    # Detailed findings by severity
    for sev in [CRITICAL, HIGH, MEDIUM, LOW]:
        sev_findings = by_severity.get(sev, [])
        if not sev_findings:
            continue
        lines.append(f"## {sev} Findings")
        lines.append("")
        for f in sev_findings:
            loc = f" (line {f.line})" if f.line else ""
            lines.append(f"- **[{f.check}]**{loc}: {f.message}")
        lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"  Findings written: {output_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Audit report for consistency, writing quality, and cross-reference integrity.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/audit_report.py --report-path docs/report.tex --phase full
    python scripts/audit_report.py --report-path docs/report.tex --phase 4
    python scripts/audit_report.py --report-path docs/report.md --phase 5 --findings FINDINGS.md
        """,
    )
    parser.add_argument(
        "--report-path", required=True,
        help="Path to the report file (.tex or .md)",
    )
    parser.add_argument(
        "--phase", default="full",
        help="Phase to run: 0-5 or 'full' (default: full)",
    )
    parser.add_argument(
        "--findings", default="FINDINGS.md",
        help="Output path for FINDINGS.md (default: FINDINGS.md)",
    )

    args = parser.parse_args()

    report_path = Path(args.report_path)
    findings_path = Path(args.findings)
    phase = args.phase

    if not report_path.exists():
        print(f"ERROR: Report file not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    # Determine which checks to run
    if phase == "full":
        checks_to_run = list(ALL_CHECKS.keys())
    else:
        try:
            phase_num = int(phase)
            checks_to_run = PHASE_CHECKS.get(phase_num, list(ALL_CHECKS.keys()))
        except ValueError:
            print(f"ERROR: Invalid phase '{phase}'. Use 0-5 or 'full'.", file=sys.stderr)
            sys.exit(1)

    latex = is_latex(report_path)
    text = read_report(report_path)

    print(f"Report Consistency Auditor")
    print(f"  Report:  {report_path}")
    print(f"  Format:  {'LaTeX' if latex else 'Markdown'}")
    print(f"  Phase:   {phase}")
    print(f"  Checks:  {len(checks_to_run)}")
    print()

    # Run checks
    all_findings: list[Finding] = []

    for check_name in checks_to_run:
        if check_name == "build_check":
            all_findings.extend(check_build(report_path))
        elif check_name == "page_count":
            all_findings.extend(check_page_count(report_path))
        elif check_name in ("title_check", "abstract_word_count",
                            "section_headers", "figure_table_crossrefs",
                            "citation_completeness",
                            "no_new_results_discussion", "caption_quality",
                            "url_escaping"):
            check_fn = ALL_CHECKS[check_name]
            all_findings.extend(check_fn(text, latex))
        elif check_name == "paragraph_length":
            all_findings.extend(check_paragraph_length(text))
        elif check_name == "jargon_first_use":
            all_findings.extend(check_jargon_first_use(text))
        elif check_name == "terminology_consistency":
            all_findings.extend(check_terminology_consistency(text))

    # Write FINDINGS.md
    write_findings_md(all_findings, findings_path, report_path, phase)

    # Print summary
    crit = sum(1 for f in all_findings if f.severity == CRITICAL)
    high = sum(1 for f in all_findings if f.severity == HIGH)
    med = sum(1 for f in all_findings if f.severity == MEDIUM)
    low = sum(1 for f in all_findings if f.severity == LOW)
    passed = sum(1 for f in all_findings if f.severity == "PASS")

    print()
    print("=" * 60)
    print("REPORT CONSISTENCY AUDIT")
    print("=" * 60)
    print(f"  CRITICAL: {crit}")
    print(f"  HIGH:     {high}")
    print(f"  MEDIUM:   {med}")
    print(f"  LOW:      {low}")
    print(f"  PASS:     {passed}")
    print("-" * 60)

    if crit + high > 0:
        print(f"  RESULT: FAIL ({crit} critical, {high} high)")
        print("=" * 60)
        sys.exit(1)
    else:
        print("  RESULT: PASS")
        print("=" * 60)
        sys.exit(0)


if __name__ == "__main__":
    main()
'''


def main() -> None:
    parser = argparse.ArgumentParser(
        description="G13: Generate report consistency auditor from project.yaml"
    )
    parser.add_argument("project_yaml", help="Path to project.yaml")
    parser.add_argument(
        "--output", default="scripts/audit_report.py",
        help="Output path for audit_report.py (default: scripts/audit_report.py)",
    )
    args = parser.parse_args()

    project = load_project(args.project_yaml)
    generate_report_auditor(project, args.output)


if __name__ == "__main__":
    main()
