#!/usr/bin/env python3
"""gen_data_report_checker.py — G14: Generate data-vs-report numeric consistency checker.

Reads the artifact and audit configuration from project.yaml and produces a
check_data_report.py script that cross-references numeric claims in report files
(LaTeX .tex or Markdown .md) against source data artifacts (CSVs, JSONs).

Usage:
    python scripts/generators/gen_data_report_checker.py project.yaml [--output scripts/check_data_report.py]
"""
import argparse
from pathlib import Path

import yaml


def load_project(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_data_report_checker(project: dict, output_path: str) -> str:
    """Generate check_data_report.py content from project.yaml."""
    artifacts = project.get("artifacts", {})
    audit = project.get("audit", {})
    project_name = project.get("project", {}).get("name", "Experiment")

    # Extract tolerance config from project.yaml audit section
    tolerances = audit.get("tolerances", {})
    default_tol = tolerances.get("default", 0.01)
    percent_tol = tolerances.get("percent", 0.5)
    count_tol = tolerances.get("count", 0)
    float_tol = tolerances.get("float", 0.005)

    # Metric keywords that the checker will search for
    metric_keywords = audit.get("metric_keywords", [
        "accuracy", "precision", "recall", "f1", "auc", "roc",
        "loss", "error", "rmse", "mae", "mse", "r2", "r_squared",
        "silhouette", "inertia", "nmi", "ari", "purity",
        "mean", "median", "std", "variance", "min", "max",
        "count", "total", "sum", "ratio", "rate", "score",
        "improvement", "reduction", "increase", "decrease", "delta",
        "baseline", "best", "worst", "average", "p_value", "p-value",
    ])

    # Magnitude plausibility threshold
    magnitude_factor = audit.get("magnitude_plausibility_factor", 2.0)

    # Build manifest filename
    manifest_file = artifacts.get("manifest_file", "EXECUTION_MANIFEST.json")

    # Build the metric keywords as a Python list literal
    kw_lines = []
    for i in range(0, len(metric_keywords), 5):
        chunk = metric_keywords[i:i + 5]
        kw_lines.append("        " + ", ".join(f'"{k}"' for k in chunk) + ",")
    kw_block = "\n".join(kw_lines)

    content = f'''#!/usr/bin/env python3
"""check_data_report.py — Cross-reference numeric claims in reports against source data.

Auto-generated by gen_data_report_checker.py from project.yaml.
Re-run generator after changing project.yaml audit configuration.

Project: {project_name}

This script:
  1. Reads the EXECUTION_MANIFEST to find artifact-to-report-section mappings.
  2. Extracts numeric claims from report files (LaTeX .tex or Markdown .md).
  3. Loads corresponding output artifacts (CSVs, JSONs).
  4. Cross-references numbers against source data.
  5. Flags mismatches beyond configurable rounding tolerance.
  6. Reports PASS/FAIL per check with specific line numbers.
  7. Outputs a structured JSON findings report and human-readable summary.

Exit codes:
  0 — All checks passed
  1 — One or more checks failed
"""
import argparse
import csv
import json
import math
import os
import re
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Configuration (derived from project.yaml at generation time)
# ---------------------------------------------------------------------------

MANIFEST_FILE = "{manifest_file}"

TOLERANCES = {{
    "default": {default_tol},
    "percent": {percent_tol},
    "count": {count_tol},
    "float": {float_tol},
}}

METRIC_KEYWORDS = [
{kw_block}
]

MAGNITUDE_PLAUSIBILITY_FACTOR = {magnitude_factor}

# Regex for matching sign-related language in surrounding context
POSITIVE_WORDS = re.compile(
    r"\\b(improv|increas|gain|better|higher|boost|rise|grew|growth)\\b", re.IGNORECASE
)
NEGATIVE_WORDS = re.compile(
    r"\\b(decreas|reduc|lower|worse|drop|decline|fell|loss|degrad)\\b", re.IGNORECASE
)


# ---------------------------------------------------------------------------
# Number extraction
# ---------------------------------------------------------------------------

# Matches numbers in text, including optional sign, decimals, and percentages
# Captures: optional sign, digits with optional decimal, optional percent sign
_NUMBER_RE = re.compile(
    r"(?<![\\w\\\\])"          # not preceded by word char or backslash
    r"([+-])?"                # optional sign
    r"(\\d{{1,3}}"            # leading digits (1-3)
    r"(?:,\\d{{3}})*"         # optional comma-separated groups
    r"(?:\\.\\d+)?)"          # optional decimal part
    r"(%?)"                   # optional percent sign
    r"(?![\\w])"              # not followed by word char
)

# LaTeX-specific: \\num{{...}}, \\SI{{...}}, or $...$
_LATEX_NUM_RE = re.compile(
    r"\\\\(?:num|SI)\\{{([^{{}}]+)\\}}"  # \\num{{1.23}} or \\SI{{1.23}}
    r"|"
    r"\\$([^$]+)\\$"                     # inline math $1.23$
)


def parse_number(raw: str) -> float | None:
    """Parse a raw number string (with optional commas) into a float."""
    cleaned = raw.replace(",", "").strip()
    try:
        return float(cleaned)
    except ValueError:
        return None


def extract_numbers_from_line(line: str, line_num: int, is_latex: bool = False) -> list[dict]:
    """Extract all numeric values from a single line of text.

    Returns a list of dicts with keys:
      value     — the parsed float
      raw       — the original matched text
      is_pct    — True if the number had a % sign
      sign      — '+', '-', or None
      line_num  — 1-based line number in the file
      context   — surrounding text snippet (up to 80 chars each side)
      metric    — best-guess metric keyword found nearby, or None
    """
    results = []

    # For LaTeX, also extract from \\num{{}} and inline math
    if is_latex:
        for m in _LATEX_NUM_RE.finditer(line):
            inner = m.group(1) or m.group(2) or ""
            for sub_m in _NUMBER_RE.finditer(inner):
                val = parse_number(sub_m.group(2))
                if val is not None:
                    sign = sub_m.group(1)
                    if sign == "-":
                        val = -val
                    results.append(_build_number_entry(
                        val, sub_m.group(0), sub_m.group(3) == "%",
                        sign, line_num, line,
                    ))

    for m in _NUMBER_RE.finditer(line):
        val = parse_number(m.group(2))
        if val is None:
            continue
        sign = m.group(1)
        if sign == "-":
            val = -val
        results.append(_build_number_entry(
            val, m.group(0), m.group(3) == "%",
            sign, line_num, line,
        ))

    return results


def _build_number_entry(
    value: float, raw: str, is_pct: bool, sign: str | None,
    line_num: int, line: str,
) -> dict:
    """Build a structured number entry with context and metric guess."""
    # Find the nearest metric keyword in the line
    metric = _find_nearest_metric(line, raw)
    # Build a short context window
    idx = line.find(raw)
    start = max(0, idx - 80)
    end = min(len(line), idx + len(raw) + 80)
    context = line[start:end].strip()

    return {{
        "value": value,
        "raw": raw,
        "is_pct": is_pct,
        "sign": sign,
        "line_num": line_num,
        "context": context,
        "metric": metric,
    }}


def _find_nearest_metric(line: str, raw: str) -> str | None:
    """Find the closest metric keyword to the raw number text in the line."""
    line_lower = line.lower()
    idx = line_lower.find(raw.lower())
    best = None
    best_dist = float("inf")

    for kw in METRIC_KEYWORDS:
        kw_lower = kw.lower()
        pos = line_lower.find(kw_lower)
        if pos == -1:
            continue
        dist = abs(pos - idx)
        if dist < best_dist:
            best_dist = dist
            best = kw
    return best


# ---------------------------------------------------------------------------
# Report file reading
# ---------------------------------------------------------------------------

def read_report(report_path: Path) -> list[dict]:
    """Read a report file and extract all numeric claims.

    Supports .tex (LaTeX) and .md (Markdown) files.
    Returns a list of number-entry dicts.
    """
    text = report_path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    is_latex = report_path.suffix.lower() in (".tex", ".latex")

    all_numbers = []
    for i, line in enumerate(lines, start=1):
        # Skip comment lines
        if is_latex and line.strip().startswith("%"):
            continue
        if not is_latex and line.strip().startswith("<!--"):
            continue

        entries = extract_numbers_from_line(line, i, is_latex=is_latex)
        all_numbers.extend(entries)

    return all_numbers


# ---------------------------------------------------------------------------
# Data artifact loading
# ---------------------------------------------------------------------------

def load_csv_numbers(csv_path: Path) -> dict[str, list[float]]:
    """Load all numeric columns from a CSV file.

    Returns a dict mapping column_name -> list of float values.
    """
    result: dict[str, list[float]] = {{}}
    try:
        with open(csv_path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                for col, val in row.items():
                    if col is None:
                        continue
                    parsed = parse_number(val)
                    if parsed is not None:
                        result.setdefault(col, []).append(parsed)
    except Exception as e:
        print(f"  WARNING: Could not read CSV {{csv_path}}: {{e}}", file=sys.stderr)
    return result


def load_json_numbers(json_path: Path) -> dict[str, float]:
    """Load numeric values from a JSON file (flat or one-level nested).

    Returns a dict mapping dotted-key-path -> float value.
    """
    result: dict[str, float] = {{}}
    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        _flatten_json(data, "", result)
    except Exception as e:
        print(f"  WARNING: Could not read JSON {{json_path}}: {{e}}", file=sys.stderr)
    return result


def _flatten_json(obj: Any, prefix: str, out: dict[str, float]) -> None:
    """Recursively flatten a JSON object into dotted-key -> float pairs."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            key = f"{{prefix}}.{{k}}" if prefix else k
            _flatten_json(v, key, out)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            key = f"{{prefix}}[{{i}}]"
            _flatten_json(v, key, out)
    elif isinstance(obj, (int, float)) and not isinstance(obj, bool):
        out[prefix] = float(obj)


def load_artifact_numbers(artifact_path: Path) -> dict[str, Any]:
    """Load numeric data from an artifact file (CSV or JSON).

    Returns a dict with:
      'source': file path string
      'type': 'csv' or 'json'
      'data': the loaded data structure
    """
    suffix = artifact_path.suffix.lower()
    if suffix == ".csv":
        return {{
            "source": str(artifact_path),
            "type": "csv",
            "data": load_csv_numbers(artifact_path),
        }}
    elif suffix == ".json":
        return {{
            "source": str(artifact_path),
            "type": "json",
            "data": load_json_numbers(artifact_path),
        }}
    else:
        return {{"source": str(artifact_path), "type": "unknown", "data": {{}}}}


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def load_manifest(manifest_path: Path) -> dict:
    """Load the execution manifest.

    Expected structure:
    {{
        "mappings": [
            {{
                "artifact": "outputs/part1/metrics.csv",
                "report_section": "Results",
                "report_file": "docs/report.tex",
                "metrics": ["accuracy", "f1"]
            }},
            ...
        ]
    }}

    Falls back to scanning outputs/ if no manifest is found.
    """
    if manifest_path.exists():
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
            return data
        except (json.JSONDecodeError, KeyError) as e:
            print(f"  WARNING: Could not parse manifest {{manifest_path}}: {{e}}",
                  file=sys.stderr)
    return {{}}


# ---------------------------------------------------------------------------
# Consistency checks
# ---------------------------------------------------------------------------

def get_tolerance(metric: str | None) -> float:
    """Get the appropriate tolerance for a given metric name."""
    if metric is None:
        return TOLERANCES["default"]

    metric_lower = metric.lower()

    # Percentage metrics
    if any(kw in metric_lower for kw in ("percent", "rate", "ratio", "%")):
        return TOLERANCES["percent"]

    # Count metrics (integers)
    if any(kw in metric_lower for kw in ("count", "total", "num", "n_")):
        return TOLERANCES["count"]

    # General float metrics
    return TOLERANCES["float"]


def numbers_match(report_val: float, data_val: float, tolerance: float) -> bool:
    """Check if two numbers match within tolerance.

    Uses absolute tolerance for small numbers and relative tolerance for large ones.
    """
    if data_val == 0 and report_val == 0:
        return True
    if data_val == 0:
        return abs(report_val) <= tolerance

    # Relative difference
    rel_diff = abs(report_val - data_val) / max(abs(data_val), 1e-12)
    # Absolute difference
    abs_diff = abs(report_val - data_val)

    # Pass if either absolute or relative is within tolerance
    return abs_diff <= tolerance or rel_diff <= tolerance


def check_sign_consistency(entry: dict, data_val: float) -> dict | None:
    """Check that sign language in context matches the actual delta sign.

    Returns a finding dict if inconsistent, else None.
    """
    context = entry.get("context", "")
    value = entry["value"]

    # Only check if we can infer expected sign from context
    has_positive = POSITIVE_WORDS.search(context)
    has_negative = NEGATIVE_WORDS.search(context)

    if has_positive and not has_negative:
        # Context implies improvement/increase — value should be positive or data > 0
        if value < 0:
            return {{
                "type": "sign_inconsistency",
                "severity": "WARNING",
                "line_num": entry["line_num"],
                "message": (
                    f"Context suggests positive change but value is {{value}} "
                    f"(line {{entry['line_num']}})"
                ),
                "context": context,
                "report_value": value,
                "data_value": data_val,
            }}
    elif has_negative and not has_positive:
        # Context implies reduction/decrease — value should be negative or decreasing
        if value > 0 and entry.get("metric") and "loss" not in entry["metric"].lower():
            return {{
                "type": "sign_inconsistency",
                "severity": "WARNING",
                "line_num": entry["line_num"],
                "message": (
                    f"Context suggests negative change but value is {{value}} "
                    f"(line {{entry['line_num']}})"
                ),
                "context": context,
                "report_value": value,
                "data_value": data_val,
            }}

    return None


def check_magnitude_plausibility(
    entry: dict, data_val: float, factor: float = MAGNITUDE_PLAUSIBILITY_FACTOR
) -> dict | None:
    """Flag if report value differs from data value by more than `factor`x.

    Returns a finding dict if implausible, else None.
    """
    if data_val == 0 or entry["value"] == 0:
        return None

    ratio = abs(entry["value"] / data_val)
    if ratio > factor or ratio < (1.0 / factor):
        return {{
            "type": "magnitude_implausible",
            "severity": "WARNING",
            "line_num": entry["line_num"],
            "message": (
                f"Report value {{entry['value']}} differs from data {{data_val}} "
                f"by factor {{ratio:.2f}}x (threshold: {{factor}}x) "
                f"(line {{entry['line_num']}})"
            ),
            "context": entry["context"],
            "report_value": entry["value"],
            "data_value": data_val,
            "ratio": ratio,
        }}
    return None


def find_best_data_match(
    entry: dict, artifact_data: dict[str, Any]
) -> tuple[str | None, float | None]:
    """Find the best matching data value for a report number entry.

    Looks in artifact data for a key matching the entry's metric keyword,
    and returns the closest value.

    Returns (matched_key, matched_value) or (None, None).
    """
    metric = entry.get("metric")
    value = entry["value"]

    if not artifact_data:
        return None, None

    best_key = None
    best_val = None
    best_diff = float("inf")

    for key, data_val in artifact_data.items():
        # If metric keyword matches key name, prioritize it
        key_lower = key.lower()
        metric_bonus = 0
        if metric and metric.lower() in key_lower:
            metric_bonus = 1000  # large bonus for keyword match

        if isinstance(data_val, list):
            # For CSV columns: check aggregates (last value, mean, min, max)
            candidates = []
            if data_val:
                candidates.append(("last", data_val[-1]))
                candidates.append(("mean", sum(data_val) / len(data_val)))
                candidates.append(("min", min(data_val)))
                candidates.append(("max", max(data_val)))
            for label, cand in candidates:
                diff = abs(value - cand)
                score = diff - metric_bonus
                if score < best_diff:
                    best_diff = score
                    best_key = f"{{key}}.{{label}}"
                    best_val = cand
        elif isinstance(data_val, (int, float)):
            diff = abs(value - data_val)
            score = diff - metric_bonus
            if score < best_diff:
                best_diff = score
                best_key = key
                best_val = data_val

    return best_key, best_val


# ---------------------------------------------------------------------------
# Main checking pipeline
# ---------------------------------------------------------------------------

def run_checks(
    report_path: Path,
    outputs_dir: Path,
    manifest_path: Path | None = None,
) -> list[dict]:
    """Run all data-vs-report consistency checks.

    Returns a list of finding dicts.
    """
    findings: list[dict] = []

    # Step 1: Load manifest
    effective_manifest = None
    if manifest_path and manifest_path.exists():
        effective_manifest = load_manifest(manifest_path)
    elif (outputs_dir / MANIFEST_FILE).exists():
        effective_manifest = load_manifest(outputs_dir / MANIFEST_FILE)
    elif Path(MANIFEST_FILE).exists():
        effective_manifest = load_manifest(Path(MANIFEST_FILE))

    # Step 2: Extract numbers from report
    if not report_path.exists():
        findings.append({{
            "type": "error",
            "severity": "FAIL",
            "message": f"Report file not found: {{report_path}}",
            "line_num": 0,
        }})
        return findings

    report_numbers = read_report(report_path)
    if not report_numbers:
        findings.append({{
            "type": "info",
            "severity": "PASS",
            "message": "No numeric claims found in report.",
            "line_num": 0,
        }})
        return findings

    print(f"  Extracted {{len(report_numbers)}} numeric values from {{report_path}}")

    # Step 3: Collect all artifact data
    all_artifact_data: dict[str, Any] = {{}}

    # From manifest mappings
    if effective_manifest and "mappings" in effective_manifest:
        for mapping in effective_manifest["mappings"]:
            artifact_rel = mapping.get("artifact", "")
            artifact_path = outputs_dir / artifact_rel
            if not artifact_path.exists():
                artifact_path = Path(artifact_rel)
            if artifact_path.exists():
                loaded = load_artifact_numbers(artifact_path)
                data = loaded.get("data", {{}})
                if isinstance(data, dict):
                    all_artifact_data.update(data)
            else:
                findings.append({{
                    "type": "missing_artifact",
                    "severity": "WARNING",
                    "message": f"Artifact not found: {{artifact_rel}}",
                    "line_num": 0,
                }})

    # Also scan outputs_dir for any CSV/JSON files not in manifest
    if outputs_dir.exists():
        for fpath in sorted(outputs_dir.rglob("*")):
            if fpath.suffix.lower() in (".csv", ".json") and fpath.is_file():
                loaded = load_artifact_numbers(fpath)
                data = loaded.get("data", {{}})
                if isinstance(data, dict):
                    # Prefix with relative path to avoid collisions
                    prefix = str(fpath.relative_to(outputs_dir)).replace(os.sep, ".")
                    prefix = prefix.rsplit(".", 1)[0]  # remove extension
                    for k, v in data.items():
                        all_artifact_data[f"{{prefix}}.{{k}}"] = v

    if not all_artifact_data:
        findings.append({{
            "type": "warning",
            "severity": "WARNING",
            "message": (
                "No artifact data found. Ensure outputs directory contains "
                "CSV/JSON files or that the manifest points to valid artifacts."
            ),
            "line_num": 0,
        }})
        return findings

    print(f"  Loaded {{len(all_artifact_data)}} data points from artifacts")

    # Step 4: Cross-reference each report number against data
    checked = 0
    matched = 0

    for entry in report_numbers:
        # Skip very common numbers that are unlikely to be metrics
        # (e.g., section numbers, years, reference numbers)
        if entry["value"] in (0, 1, 2, 3) and entry["metric"] is None:
            continue
        if 1900 <= entry["value"] <= 2100 and entry["metric"] is None:
            continue  # likely a year

        best_key, best_val = find_best_data_match(entry, all_artifact_data)

        if best_key is None or best_val is None:
            continue  # no matching data found — skip silently

        checked += 1
        tol = get_tolerance(entry.get("metric"))

        if numbers_match(entry["value"], best_val, tol):
            matched += 1
            findings.append({{
                "type": "numeric_match",
                "severity": "PASS",
                "line_num": entry["line_num"],
                "message": (
                    f"Line {{entry['line_num']}}: report={{entry['value']}} "
                    f"matches data={{best_val}} (key={{best_key}}, tol={{tol}})"
                ),
                "report_value": entry["value"],
                "data_value": best_val,
                "data_key": best_key,
                "tolerance": tol,
                "metric": entry.get("metric"),
            }})
        else:
            findings.append({{
                "type": "numeric_mismatch",
                "severity": "FAIL",
                "line_num": entry["line_num"],
                "message": (
                    f"Line {{entry['line_num']}}: report={{entry['value']}} "
                    f"!= data={{best_val}} (key={{best_key}}, tol={{tol}})"
                ),
                "context": entry["context"],
                "report_value": entry["value"],
                "data_value": best_val,
                "data_key": best_key,
                "tolerance": tol,
                "metric": entry.get("metric"),
            }})

        # Additional checks
        sign_finding = check_sign_consistency(entry, best_val)
        if sign_finding:
            findings.append(sign_finding)

        mag_finding = check_magnitude_plausibility(entry, best_val)
        if mag_finding:
            findings.append(mag_finding)

    print(f"  Cross-referenced {{checked}} values, {{matched}} matched")

    return findings


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def write_findings_json(findings: list[dict], output_path: Path) -> None:
    """Write findings to a structured JSON file."""
    summary = {{
        "total": len(findings),
        "pass": sum(1 for f in findings if f["severity"] == "PASS"),
        "fail": sum(1 for f in findings if f["severity"] == "FAIL"),
        "warning": sum(1 for f in findings if f["severity"] == "WARNING"),
    }}
    report = {{
        "summary": summary,
        "findings": findings,
    }}
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, default=str) + "\\n")
    print(f"  JSON findings written: {{output_path}}")


def print_human_summary(findings: list[dict]) -> None:
    """Print a human-readable summary of findings."""
    passes = [f for f in findings if f["severity"] == "PASS"]
    fails = [f for f in findings if f["severity"] == "FAIL"]
    warnings = [f for f in findings if f["severity"] == "WARNING"]

    print()
    print("=" * 70)
    print("DATA vs REPORT CONSISTENCY CHECK")
    print("=" * 70)
    print(f"  PASS:    {{len(passes)}}")
    print(f"  FAIL:    {{len(fails)}}")
    print(f"  WARNING: {{len(warnings)}}")
    print("-" * 70)

    if fails:
        print()
        print("FAILURES:")
        for f in fails:
            print(f"  [FAIL] {{f['message']}}")
            if "context" in f:
                ctx = f["context"][:120]
                print(f"         Context: {{ctx}}")
        print()

    if warnings:
        print("WARNINGS:")
        for w in warnings:
            print(f"  [WARN] {{w['message']}}")
        print()

    if not fails and not warnings:
        print("  All numeric claims consistent with source data.")
    print("=" * 70)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Check numeric consistency between report and data artifacts.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/check_data_report.py --report-path docs/report.tex --outputs-dir outputs/
    python scripts/check_data_report.py --report-path docs/report.md --outputs-dir outputs/ --findings-json findings.json
        """,
    )
    parser.add_argument(
        "--report-path", required=True,
        help="Path to the report file (.tex or .md)",
    )
    parser.add_argument(
        "--outputs-dir", default="outputs",
        help="Directory containing output artifacts (default: outputs/)",
    )
    parser.add_argument(
        "--manifest", default=None,
        help="Path to execution manifest JSON (default: auto-detect)",
    )
    parser.add_argument(
        "--findings-json", default="data_report_findings.json",
        help="Path for JSON findings output (default: data_report_findings.json)",
    )

    args = parser.parse_args()

    report_path = Path(args.report_path)
    outputs_dir = Path(args.outputs_dir)
    manifest_path = Path(args.manifest) if args.manifest else None
    findings_json_path = Path(args.findings_json)

    print(f"Data-vs-Report Consistency Checker")
    print(f"  Report:   {{report_path}}")
    print(f"  Outputs:  {{outputs_dir}}")
    print(f"  Manifest: {{manifest_path or '(auto-detect)'}}")
    print()

    # Run checks
    findings = run_checks(report_path, outputs_dir, manifest_path)

    # Output results
    write_findings_json(findings, findings_json_path)
    print_human_summary(findings)

    # Exit code
    has_failures = any(f["severity"] == "FAIL" for f in findings)
    sys.exit(1 if has_failures else 0)


if __name__ == "__main__":
    main()
'''

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    out.chmod(0o755)

    # Summary
    print(f"Generated: {output_path}")
    print(f"  Project:    {project_name}")
    print(f"  Tolerances: default={default_tol}, percent={percent_tol}, "
          f"count={count_tol}, float={float_tol}")
    print(f"  Keywords:   {len(metric_keywords)} metric keywords configured")
    print(f"  Magnitude:  >{magnitude_factor}x difference flagged")
    print(f"  Manifest:   {manifest_file}")
    return content


def main() -> None:
    parser = argparse.ArgumentParser(
        description="G14: Generate data-vs-report numeric consistency checker from project.yaml"
    )
    parser.add_argument("project_yaml", help="Path to project.yaml")
    parser.add_argument(
        "--output", default="scripts/check_data_report.py",
        help="Output path for check_data_report.py",
    )
    args = parser.parse_args()

    project = load_project(args.project_yaml)
    generate_data_report_checker(project, args.output)


if __name__ == "__main__":
    main()
