#!/usr/bin/env python3
"""gen_sweep.py — Generate sweep.sh from project.yaml experiment matrix.

Reads the experiment matrix from project.yaml and produces a sweep.sh script
that orchestrates all experiment combinations (methods × datasets × seeds).

Usage:
    python scripts/generators/gen_sweep.py project.yaml [--output scripts/sweep.sh]
"""
import argparse
import sys
from pathlib import Path

import yaml


def load_project(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_sweep(project: dict, output_path: str) -> str:
    """Generate sweep.sh content from project.yaml."""
    experiments = project.get("experiments", {})
    seeds = experiments.get("seeds", [42])
    parts = experiments.get("parts", [])
    project_name = project.get("project", {}).get("name", "Experiment")

    lines = [
        "#!/usr/bin/env bash",
        f"# sweep.sh — Orchestrate all experiments for {project_name}",
        "# AUTO-GENERATED by gen_sweep.py from project.yaml",
        "# Re-run generator after changing project.yaml experiment matrix.",
        "set -euo pipefail",
        "",
        f'SEEDS="{",".join(str(s) for s in seeds)}"',
        'PARTS="all"',
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"',
        "",
        "usage() {",
        '    echo "Usage: bash $0 [--parts {' + ",".join(str(i + 1) for i in range(len(parts))) + ',all}] [--seeds SEED_LIST]"',
        "    exit 1",
        "}",
        "",
        'while [[ $# -gt 0 ]]; do',
        '    case "$1" in',
        '        --parts) PARTS="$2"; shift 2 ;;',
        '        --seeds) SEEDS="$2"; shift 2 ;;',
        '        *) echo "Unknown arg: $1"; usage ;;',
        "    esac",
        "done",
        "",
        'IFS=\',\' read -ra SEED_ARRAY <<< "$SEEDS"',
        'cd "$PROJECT_DIR"',
        "export PYTHONHASHSEED=0",
        "",
    ]

    # Generate a function per part
    for i, part in enumerate(parts):
        part_num = i + 1
        part_name = part.get("name", f"part{part_num}")
        methods = part.get("methods", [])
        datasets = part.get("datasets", ["default"])
        script = part.get("script", f"scripts/run_part{part_num}.py")
        flags_template = part.get("flags", "--method {method} --seed {seed}")
        output_dir_template = part.get("output_dir", "")

        func_name = f"run_part{part_num}"
        lines.append(f"{func_name}() {{")
        lines.append(f'    echo "=== Part {part_num}: {part_name} ==="')

        # Build nested loops
        indent = "    "
        loop_vars = []

        if len(methods) > 1 or (len(methods) == 1 and "{method}" in flags_template):
            methods_str = " ".join(methods)
            lines.append(f'{indent}for method in {methods_str}; do')
            indent += "    "
            loop_vars.append("method")

        if len(datasets) > 1 or (len(datasets) == 1 and "{dataset}" in flags_template):
            datasets_str = " ".join(datasets)
            lines.append(f'{indent}for dataset in {datasets_str}; do')
            indent += "    "
            loop_vars.append("dataset")

        lines.append(f'{indent}for seed in "${{SEED_ARRAY[@]}}"; do')
        indent += "    "

        # Build the echo line
        echo_parts = []
        if "method" in loop_vars:
            echo_parts.append("$method")
        if "dataset" in loop_vars:
            echo_parts.append("$dataset")
        echo_parts.append("seed $seed")
        lines.append(f'{indent}echo "  {" / ".join(echo_parts)}"')

        # Build the command
        flags = flags_template
        flags = flags.replace("{method}", "$method")
        flags = flags.replace("{dataset}", "$dataset")
        flags = flags.replace("{seed}", "$seed")

        cmd = f'{indent}python {script} \\\n{indent}    {flags}'

        # Add output-dir if template has variable parts
        if output_dir_template and any(v in output_dir_template for v in ["{method}", "{dataset}", "{seed}"]):
            out_dir = output_dir_template
            out_dir = out_dir.replace("{part}", part_name)
            out_dir = out_dir.replace("{method}", "$method")
            out_dir = out_dir.replace("{dataset}", "$dataset")
            out_dir = out_dir.replace("{seed}", "$seed")
            cmd += f' \\\n{indent}    --output-dir "{out_dir}"'

        lines.append(cmd)

        # Close loops in reverse order
        indent = indent[:-4]
        lines.append(f"{indent}done")  # seed loop

        if "dataset" in loop_vars:
            indent = indent[:-4]
            lines.append(f"{indent}done")

        if "method" in loop_vars:
            indent = indent[:-4]
            lines.append(f"{indent}done")

        lines.append("}")
        lines.append("")

    # Generate the case statement
    lines.append('case "$PARTS" in')
    for i in range(len(parts)):
        lines.append(f"    {i + 1}) run_part{i + 1} ;;")

    # Build the 'all' case
    all_calls = "; ".join(f"run_part{i + 1}" for i in range(len(parts)))
    lines.append(f"    all) {all_calls} ;;")
    lines.append('    *) echo "Unknown part: $PARTS"; usage ;;')
    lines.append("esac")
    lines.append("")
    lines.append("echo ''")
    lines.append('echo "=== Sweep complete ==="')
    lines.append("")

    content = "\n".join(lines)

    # Write output
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    out.chmod(0o755)
    print(f"Generated: {output_path}")
    return content


def main():
    parser = argparse.ArgumentParser(description="Generate sweep.sh from project.yaml")
    parser.add_argument("project_yaml", help="Path to project.yaml")
    parser.add_argument("--output", default="scripts/sweep.sh", help="Output path for sweep.sh")
    args = parser.parse_args()

    project = load_project(args.project_yaml)
    generate_sweep(project, args.output)


if __name__ == "__main__":
    main()
