#!/usr/bin/env python3
"""gen_phase_gates.py — Generate executable phase gate scripts from project.yaml.

Reads the phase definitions from project.yaml and produces:
  - scripts/check_phase_{N}.sh for each phase
  - scripts/check_all_gates.sh that runs all gates in sequence

Usage:
    python scripts/generators/gen_phase_gates.py project.yaml [--output-dir scripts/]
"""
import argparse
from pathlib import Path

import yaml


def load_project(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def generate_phase_script(phase_num: int, phase: dict) -> str:
    """Generate a single phase gate check script."""
    name = phase.get("name", f"Phase {phase_num}")
    checks = phase.get("checks", [])

    lines = [
        "#!/usr/bin/env bash",
        f"# check_phase_{phase_num}.sh — Gate check for {name}",
        "# AUTO-GENERATED by gen_phase_gates.py from project.yaml",
        "set -euo pipefail",
        'cd "$(dirname "${BASH_SOURCE[0]}")/.."',
        "",
        f'echo "=== {name} ==="',
        "echo ''",
        "",
        "PASSED=0",
        "FAILED=0",
        "ERRORS=()",
        "",
    ]

    for i, check in enumerate(checks):
        cmd = check.get("command", "true")
        desc = check.get("description", f"Check {i + 1}")

        lines.extend([
            f'echo -n "  [{i + 1}/{len(checks)}] {desc}... "',
            f"if {cmd} > /dev/null 2>&1; then",
            '    echo "PASS"',
            "    PASSED=$((PASSED + 1))",
            "else",
            '    echo "FAIL"',
            "    FAILED=$((FAILED + 1))",
            f'    ERRORS+=("  FAIL: {desc}")',
            f'    ERRORS+=("        Command: {cmd}")',
            "fi",
            "",
        ])

    lines.extend([
        "echo ''",
        'echo "=== Results: $PASSED passed, $FAILED failed ==="',
        "",
        'if [ $FAILED -gt 0 ]; then',
        '    echo ""',
        '    echo "Failures:"',
        '    for err in "${ERRORS[@]}"; do',
        '        echo "$err"',
        "    done",
        '    echo ""',
        f'    echo "Phase gate FAILED. Fix the above issues before proceeding."',
        "    exit 1",
        "fi",
        "",
        f'echo "{name} — ALL CHECKS PASSED"',
        "",
    ])

    return "\n".join(lines)


def generate_all_gates(phases: list, output_dir: str) -> str:
    """Generate check_all_gates.sh that runs all phase gates in sequence."""
    lines = [
        "#!/usr/bin/env bash",
        "# check_all_gates.sh — Run all phase gate checks in sequence",
        "# AUTO-GENERATED by gen_phase_gates.py from project.yaml",
        "set -euo pipefail",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        "",
        "TOTAL_PASSED=0",
        "TOTAL_FAILED=0",
        "",
    ]

    for i, phase in enumerate(phases):
        name = phase.get("name", f"Phase {i}")
        lines.extend([
            f'echo ">>> Running gate {i}: {name}"',
            f'if bash "$SCRIPT_DIR/check_phase_{i}.sh"; then',
            "    TOTAL_PASSED=$((TOTAL_PASSED + 1))",
            "else",
            "    TOTAL_FAILED=$((TOTAL_FAILED + 1))",
            f'    echo "!!! Gate {i} failed — stopping."',
            "    exit 1",
            "fi",
            "echo ''",
            "",
        ])

    lines.extend([
        'echo "========================================="',
        'echo "All $TOTAL_PASSED phase gates PASSED."',
        'echo "========================================="',
        "",
    ])

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate phase gate scripts from project.yaml")
    parser.add_argument("project_yaml", help="Path to project.yaml")
    parser.add_argument("--output-dir", default="scripts", help="Output directory for gate scripts")
    args = parser.parse_args()

    project = load_project(args.project_yaml)
    phases = project.get("phases", [])
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if not phases:
        print("No phases defined in project.yaml. Nothing to generate.")
        return

    # Generate per-phase scripts
    for i, phase in enumerate(phases):
        content = generate_phase_script(i, phase)
        out_path = output_dir / f"check_phase_{i}.sh"
        out_path.write_text(content)
        out_path.chmod(0o755)
        print(f"Generated: {out_path}")

    # Generate all-gates runner
    content = generate_all_gates(phases, str(output_dir))
    out_path = output_dir / "check_all_gates.sh"
    out_path.write_text(content)
    out_path.chmod(0o755)
    print(f"Generated: {out_path}")

    print(f"\n{len(phases)} phase gate scripts + 1 all-gates runner generated.")


if __name__ == "__main__":
    main()
